// Supabase client - İleride entegre edilecek
// TODO: Supabase kurulumu yapıldığında burası güncellenecek

// import { createClient } from '@supabase/supabase-js'

// const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
// const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

// export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Şimdilik mock data için yardımcı fonksiyonlar
export const mockPhones = [
  {
    id: "1",
    brand: "Apple",
    model: "iPhone 15 Pro Max 256GB",
    colors: ["Siyah", "Beyaz", "Titanyum Mavi", "Titanyum Gri"],
    cashPrice: 115000,
    installmentRate: 1.15,
    singlePaymentRate: 1.05,
    stock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    brand: "Apple",
    model: "iPhone 15 Pro 128GB",
    colors: ["Siyah", "Beyaz", "Titanyum Mavi"],
    cashPrice: 58000,
    installmentRate: 1.15,
    singlePaymentRate: 1.05,
    stock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    brand: "Apple",
    model: "iPhone 14 128GB",
    colors: ["Siyah", "Beyaz", "Mavi", "Mor"],
    cashPrice: 45000,
    installmentRate: 1.15,
    singlePaymentRate: 1.05,
    stock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    brand: "Samsung",
    model: "Galaxy S24 Ultra 256GB",
    colors: ["Titanyum Gri", "Titanyum Mavi", "Siyah"],
    cashPrice: 55000,
    installmentRate: 1.15,
    singlePaymentRate: 1.05,
    stock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    brand: "Samsung",
    model: "Galaxy S24 128GB",
    colors: ["Mor", "Yeşil", "Beyaz"],
    cashPrice: 42000,
    installmentRate: 1.15,
    singlePaymentRate: 1.05,
    stock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    brand: "Samsung",
    model: "Galaxy A54 128GB",
    colors: ["Yeşil", "Siyah", "Beyaz"],
    cashPrice: 18000,
    installmentRate: 1.15,
    singlePaymentRate: 1.05,
    stock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    brand: "Xiaomi",
    model: "Redmi Note 13 Pro 256GB",
    colors: ["Siyah", "Mavi", "Yeşil"],
    cashPrice: 12000,
    installmentRate: 1.15,
    singlePaymentRate: 1.05,
    stock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    brand: "Xiaomi",
    model: "Xiaomi 14 Pro 256GB",
    colors: ["Beyaz", "Siyah", "Gri"],
    cashPrice: 35000,
    installmentRate: 1.15,
    singlePaymentRate: 1.05,
    stock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    brand: "Huawei",
    model: "P60 Pro 256GB",
    colors: ["Gold", "Siyah", "Gümüş"],
    cashPrice: 32000,
    installmentRate: 1.15,
    singlePaymentRate: 1.05,
    stock: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
